<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SiteContent;

class SiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Only seed if table is empty
        if (SiteContent::count() > 0) {
            $this->command->info('SiteContent table is not empty. Skipping seeder.');
            return;
        }

        $this->command->info('Seeding site contents...');

        $contents = [
            // ===== HERO SECTION =====
            [
                'key' => 'hero_title',
                'type' => 'text',
                'value' => 'Events Done Right',
                'label' => 'Hero Title',
                'section' => 'Hero Section',
                'description' => 'Main headline displayed in the hero section',
                'sort_order' => 1,
            ],
            [
                'key' => 'hero_subtitle',
                'type' => 'textarea',
                'value' => 'AO International Projects Management; (Advanced Orientation) brings years of experience in medical events to a wide range of industries — helping teams plan, manage, and deliver events that leave a mark.',
                'label' => 'Hero Subtitle',
                'section' => 'Hero Section',
                'description' => 'Description text below the main headline',
                'sort_order' => 2,
            ],
            [
                'key' => 'hero_cta_text',
                'type' => 'text',
                'value' => 'See What We Do',
                'label' => 'Hero Button Text',
                'section' => 'Hero Section',
                'description' => 'Text for the call-to-action button',
                'sort_order' => 3,
            ],
            [
                'key' => 'hero_cta_link',
                'type' => 'text',
                'value' => '#about',
                'label' => 'Hero Button Link',
                'section' => 'Hero Section',
                'description' => 'Link destination for the CTA button',
                'sort_order' => 4,
            ],
            [
                'key' => 'hero_video',
                'type' => 'video',
                'value' => 'videos/hero.mp4',
                'label' => 'Hero Background Video',
                'section' => 'Hero Section',
                'description' => 'Background video for the hero section',
                'sort_order' => 5,
            ],

            // ===== EVENTS SECTION =====
            [
                'key' => 'events_label',
                'type' => 'text',
                'value' => 'Events',
                'label' => 'Events Section Label',
                'section' => 'Events Section',
                'description' => 'Small label text above the title',
                'sort_order' => 1,
            ],
            [
                'key' => 'events_title',
                'type' => 'text',
                'value' => 'Our global events',
                'label' => 'Events Title',
                'section' => 'Events Section',
                'description' => 'Main title for the events section',
                'sort_order' => 2,
            ],
            [
                'key' => 'events_description_1',
                'type' => 'textarea',
                'value' => 'We host invitation-only events at key climate moments as well as community and partner-led gatherings in cities around the world. These moments enable guests to learn from each other, explore deal flow and create connections, encouraging collaboration.',
                'label' => 'Events Description (Paragraph 1)',
                'section' => 'Events Section',
                'description' => 'First paragraph of events description',
                'sort_order' => 3,
            ],
            [
                'key' => 'events_description_2',
                'type' => 'textarea',
                'value' => 'Trust is built in rooms, not virtual rooms. We put humanity back in the room.',
                'label' => 'Events Description (Paragraph 2)',
                'section' => 'Events Section',
                'description' => 'Second paragraph of events description',
                'sort_order' => 4,
            ],
            [
                'key' => 'events_cta_text',
                'type' => 'text',
                'value' => 'Get in touch',
                'label' => 'Events Button Text',
                'section' => 'Events Section',
                'description' => 'Text for the events section button',
                'sort_order' => 5,
            ],
            [
                'key' => 'events_image',
                'type' => 'image',
                'value' => '/images/vfc.jpg',
                'label' => 'Events Section Image',
                'section' => 'Events Section',
                'description' => 'Featured image for the events section',
                'sort_order' => 6,
            ],

            // ===== ABOUT / WHO WE ARE SECTION =====
            [
                'key' => 'about_title',
                'type' => 'text',
                'value' => 'Who We Are',
                'label' => 'About Section Title',
                'section' => 'About Section',
                'description' => 'Title for the Who We Are section',
                'sort_order' => 1,
            ],
            [
                'key' => 'about_description_1',
                'type' => 'textarea',
                'value' => 'AO International Projects Management Co. is a full-service management company specialized in marketing strategy, business process optimization, planning conferences, exhibitions, seminars, health awareness campaigns, and professional events.',
                'label' => 'About Description (Paragraph 1)',
                'section' => 'About Section',
                'description' => 'First paragraph describing the company',
                'sort_order' => 2,
            ],
            [
                'key' => 'about_description_2',
                'type' => 'textarea',
                'value' => 'AO International Projects Management is a trusted provider of comprehensive medical writing, clinical research support, and data management services. With a commitment to precision, efficiency, and affordability, we collaborate with healthcare professionals, pharmaceutical companies, and KOLs to deliver impactful, evidence-based scientific content.',
                'label' => 'About Description (Paragraph 2)',
                'section' => 'About Section',
                'description' => 'Second paragraph describing services',
                'sort_order' => 3,
            ],

            // ===== CORE SERVICES SECTION =====
            [
                'key' => 'services_title',
                'type' => 'text',
                'value' => 'Our Core Services',
                'label' => 'Services Section Title',
                'section' => 'Services Section',
                'description' => 'Main title for the services section',
                'sort_order' => 1,
            ],
            [
                'key' => 'service_1_title',
                'type' => 'text',
                'value' => 'Medical Writing Services',
                'label' => 'Service 1 Title',
                'section' => 'Services Section',
                'description' => 'Title for first service',
                'sort_order' => 2,
            ],
            [
                'key' => 'service_1_description',
                'type' => 'textarea',
                'value' => 'Manuscript writing and editing, advisory board support and documentation, conference abstracts and posters, grant writing assistance.',
                'label' => 'Service 1 Description',
                'section' => 'Services Section',
                'description' => 'Description for first service',
                'sort_order' => 3,
            ],
            [
                'key' => 'service_2_title',
                'type' => 'text',
                'value' => 'Clinical Research Support',
                'label' => 'Service 2 Title',
                'section' => 'Services Section',
                'description' => 'Title for second service',
                'sort_order' => 4,
            ],
            [
                'key' => 'service_2_description',
                'type' => 'textarea',
                'value' => 'Protocol development, study documentation, investigator brochures, study proposals, protocols, CSR, SAR, SAP, and conference abstracts and presentations.',
                'label' => 'Service 2 Description',
                'section' => 'Services Section',
                'description' => 'Description for second service',
                'sort_order' => 5,
            ],
            [
                'key' => 'service_3_title',
                'type' => 'text',
                'value' => 'Data Management & Statistical Analysis',
                'label' => 'Service 3 Title',
                'section' => 'Services Section',
                'description' => 'Title for third service',
                'sort_order' => 6,
            ],
            [
                'key' => 'service_3_description',
                'type' => 'textarea',
                'value' => 'Comprehensive data management, statistical analysis, and reporting.',
                'label' => 'Service 3 Description',
                'section' => 'Services Section',
                'description' => 'Description for third service',
                'sort_order' => 7,
            ],
            [
                'key' => 'service_4_title',
                'type' => 'text',
                'value' => 'Medical Affairs Services & Training',
                'label' => 'Service 4 Title',
                'section' => 'Services Section',
                'description' => 'Title for fourth service',
                'sort_order' => 8,
            ],
            [
                'key' => 'service_4_description',
                'type' => 'textarea',
                'value' => 'Medical education workshops (CME), customized training programs for medical affairs professionals.',
                'label' => 'Service 4 Description',
                'section' => 'Services Section',
                'description' => 'Description for fourth service',
                'sort_order' => 9,
            ],
            [
                'key' => 'service_5_title',
                'type' => 'text',
                'value' => 'Infographic & Visual Solutions',
                'label' => 'Service 5 Title',
                'section' => 'Services Section',
                'description' => 'Title for fifth service',
                'sort_order' => 10,
            ],
            [
                'key' => 'service_5_description',
                'type' => 'textarea',
                'value' => 'Professional infographic creation to simplify complex medical data and graphical abstracts.',
                'label' => 'Service 5 Description',
                'section' => 'Services Section',
                'description' => 'Description for fifth service',
                'sort_order' => 11,
            ],
            [
                'key' => 'service_6_title',
                'type' => 'text',
                'value' => 'Publication Planning & Journal Compliance',
                'label' => 'Service 6 Title',
                'section' => 'Services Section',
                'description' => 'Title for sixth service',
                'sort_order' => 12,
            ],
            [
                'key' => 'service_6_description',
                'type' => 'textarea',
                'value' => 'Strategic publication plans, journal selection and compliance with editorial requirements, journal submission and follow-up.',
                'label' => 'Service 6 Description',
                'section' => 'Services Section',
                'description' => 'Description for sixth service',
                'sort_order' => 13,
            ],
            [
                'key' => 'service_7_title',
                'type' => 'text',
                'value' => 'Digital Solutions',
                'label' => 'Service 7 Title',
                'section' => 'Services Section',
                'description' => 'Title for seventh service',
                'sort_order' => 14,
            ],
            [
                'key' => 'service_7_description',
                'type' => 'textarea',
                'value' => 'Development of medical registries, decision support tools, patient education apps, collaborative platforms for multidisciplinary teams, mobile apps for preoperative assessment.',
                'label' => 'Service 7 Description',
                'section' => 'Services Section',
                'description' => 'Description for seventh service',
                'sort_order' => 15,
            ],
            [
                'key' => 'service_8_title',
                'type' => 'text',
                'value' => 'Conference & Event Support',
                'label' => 'Service 8 Title',
                'section' => 'Services Section',
                'description' => 'Title for eighth service',
                'sort_order' => 16,
            ],
            [
                'key' => 'service_8_description',
                'type' => 'textarea',
                'value' => 'Abstract booklets and proceedings, scientific coverage of key sessions, design of presentation materials (slides, posters, or reports).',
                'label' => 'Service 8 Description',
                'section' => 'Services Section',
                'description' => 'Description for eighth service',
                'sort_order' => 17,
            ],

            // ===== WHY CHOOSE US SECTION =====
            [
                'key' => 'why_title',
                'type' => 'text',
                'value' => 'Why Choose Us?',
                'label' => 'Why Choose Us Title',
                'section' => 'Why Choose Us',
                'description' => 'Title for the Why Choose Us section',
                'sort_order' => 1,
            ],
            [
                'key' => 'why_image',
                'type' => 'image',
                'value' => 'images/whyus.jpg',
                'label' => 'Why Choose Us Image',
                'section' => 'Why Choose Us',
                'description' => 'Featured image for this section',
                'sort_order' => 2,
            ],
            [
                'key' => 'why_point_1_title',
                'type' => 'text',
                'value' => 'Unmatched Quality',
                'label' => 'Point 1 Title',
                'section' => 'Why Choose Us',
                'description' => 'First selling point title',
                'sort_order' => 3,
            ],
            [
                'key' => 'why_point_1_description',
                'type' => 'text',
                'value' => 'Every project is handled with scientific precision and attention to detail.',
                'label' => 'Point 1 Description',
                'section' => 'Why Choose Us',
                'description' => 'First selling point description',
                'sort_order' => 4,
            ],
            [
                'key' => 'why_point_2_title',
                'type' => 'text',
                'value' => 'Timely Delivery',
                'label' => 'Point 2 Title',
                'section' => 'Why Choose Us',
                'description' => 'Second selling point title',
                'sort_order' => 5,
            ],
            [
                'key' => 'why_point_2_description',
                'type' => 'text',
                'value' => 'We meet deadlines without compromise.',
                'label' => 'Point 2 Description',
                'section' => 'Why Choose Us',
                'description' => 'Second selling point description',
                'sort_order' => 6,
            ],
            [
                'key' => 'why_point_3_title',
                'type' => 'text',
                'value' => 'Cost-Effective Solutions',
                'label' => 'Point 3 Title',
                'section' => 'Why Choose Us',
                'description' => 'Third selling point title',
                'sort_order' => 7,
            ],
            [
                'key' => 'why_point_3_description',
                'type' => 'text',
                'value' => 'Affordability with zero compromise on quality.',
                'label' => 'Point 3 Description',
                'section' => 'Why Choose Us',
                'description' => 'Third selling point description',
                'sort_order' => 8,
            ],

            // ===== CLIENTS SECTION =====
            [
                'key' => 'clients_title',
                'type' => 'text',
                'value' => 'Our Clients',
                'label' => 'Clients Section Title',
                'section' => 'Clients Section',
                'description' => 'Title for the clients/partners section',
                'sort_order' => 1,
            ],
            [
                'key' => 'clients_subtitle',
                'type' => 'text',
                'value' => 'We are working with a range of incredible global partners including:',
                'label' => 'Clients Section Subtitle',
                'section' => 'Clients Section',
                'description' => 'Subtitle text below the title',
                'sort_order' => 2,
            ],

            // ===== OUR WORK SECTION =====
            [
                'key' => 'work_title',
                'type' => 'text',
                'value' => 'Our Work',
                'label' => 'Our Work Section Title',
                'section' => 'Our Work Section',
                'description' => 'Title for the previous work/portfolio section',
                'sort_order' => 1,
            ],

            // ===== METRICS SECTION =====
            [
                'key' => 'metrics_label',
                'type' => 'text',
                'value' => 'Our Metrics + Impact',
                'label' => 'Metrics Section Label',
                'section' => 'Metrics Section',
                'description' => 'Small label text above metrics title',
                'sort_order' => 1,
            ],
            [
                'key' => 'metrics_title',
                'type' => 'text',
                'value' => 'The following medical event outcomes have been established:',
                'label' => 'Metrics Section Title',
                'section' => 'Metrics Section',
                'description' => 'Main title for the metrics section',
                'sort_order' => 2,
            ],
            [
                'key' => 'metric_1_value',
                'type' => 'number',
                'value' => '97',
                'label' => 'Metric 1 Value',
                'section' => 'Metrics Section',
                'description' => 'Percentage value for first metric (Knowledge Retention)',
                'sort_order' => 3,
            ],
            [
                'key' => 'metric_1_label',
                'type' => 'text',
                'value' => 'Knowledge Retention',
                'label' => 'Metric 1 Label',
                'section' => 'Metrics Section',
                'description' => 'Label for first metric',
                'sort_order' => 4,
            ],
            [
                'key' => 'metric_1_description',
                'type' => 'text',
                'value' => 'of participants reported improved understanding of clinical procedures',
                'label' => 'Metric 1 Description',
                'section' => 'Metrics Section',
                'description' => 'Description text for first metric',
                'sort_order' => 5,
            ],
            [
                'key' => 'metric_2_value',
                'type' => 'number',
                'value' => '98',
                'label' => 'Metric 2 Value',
                'section' => 'Metrics Section',
                'description' => 'Value for second metric (NPS Score)',
                'sort_order' => 6,
            ],
            [
                'key' => 'metric_2_label',
                'type' => 'text',
                'value' => 'NPS Score',
                'label' => 'Metric 2 Label',
                'section' => 'Metrics Section',
                'description' => 'Label for second metric',
                'sort_order' => 7,
            ],
            [
                'key' => 'metric_2_description',
                'type' => 'text',
                'value' => 'A blended Net Promoter Score of 98 across international AO events',
                'label' => 'Metric 2 Description',
                'section' => 'Metrics Section',
                'description' => 'Description text for second metric',
                'sort_order' => 8,
            ],
            [
                'key' => 'metric_3_value',
                'type' => 'number',
                'value' => '94',
                'label' => 'Metric 3 Value',
                'section' => 'Metrics Section',
                'description' => 'Percentage value for third metric (Global Collaboration)',
                'sort_order' => 9,
            ],
            [
                'key' => 'metric_3_label',
                'type' => 'text',
                'value' => 'Global Collaboration',
                'label' => 'Metric 3 Label',
                'section' => 'Metrics Section',
                'description' => 'Label for third metric',
                'sort_order' => 10,
            ],
            [
                'key' => 'metric_3_description',
                'type' => 'text',
                'value' => 'of attendees made a new global research or clinical connection',
                'label' => 'Metric 3 Description',
                'section' => 'Metrics Section',
                'description' => 'Description text for third metric',
                'sort_order' => 11,
            ],

            // ===== CONTACT SECTION =====
            [
                'key' => 'contact_title',
                'type' => 'text',
                'value' => 'Contact Us',
                'label' => 'Contact Section Title',
                'section' => 'Contact Section',
                'description' => 'Title for the contact section',
                'sort_order' => 1,
            ],
            [
                'key' => 'contact_subtitle',
                'type' => 'text',
                'value' => 'Have questions or ideas? Reach out and let\'s connect!',
                'label' => 'Contact Section Subtitle',
                'section' => 'Contact Section',
                'description' => 'Subtitle text for the contact section',
                'sort_order' => 2,
            ],
            [
                'key' => 'contact_cta_text',
                'type' => 'text',
                'value' => 'Send Message',
                'label' => 'Contact Button Text',
                'section' => 'Contact Section',
                'description' => 'Text for the contact form submit button',
                'sort_order' => 3,
            ],
            [
                'key' => 'contact_email',
                'type' => 'email',
                'value' => 'info@aofoundation.com',
                'label' => 'Contact Email',
                'section' => 'Contact Section',
                'description' => 'Main contact email address',
                'sort_order' => 4,
            ],
            [
                'key' => 'contact_phone',
                'type' => 'text',
                'value' => '',
                'label' => 'Contact Phone',
                'section' => 'Contact Section',
                'description' => 'Main contact phone number',
                'sort_order' => 5,
            ],
        ];

        foreach ($contents as $content) {
            SiteContent::create($content);
        }

        $this->command->info('Successfully seeded ' . count($contents) . ' content items.');
    }
}